<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon />
    <StartupObject>TemperatureMonitor.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot.WinForms" Version="5.0.*" />
    <PackageReference Include="System.IO.Ports" Version="8.*" />
  </ItemGroup>

</Project>
